Users can now download the logs of their runs, even if the run crashed. Fixed a bug where Logger instances were mixing handlers.

diff --git a/docker-healthcheck b/docker-healthcheck
--- a/docker-healthcheck
+++ b/docker-healthcheck
@@ -1,15 +1,23 @@
 #!/bin/bash
 
 function api_failed() {
-	echo "API Healthcheck failed.";
+	echo "API Healthcheck failed: \"$1\"";
 	exit 1;
 }
 
 function dashboard_failed() {
-	echo "Dashboard Healthcheck failed.";
+	echo "Dashboard Healthcheck failed: \"$1\"";
 	exit 2;
 }
 
-curl -fs "http://localhost:$FAST_API_PORT/healthcheck" || api_failed
-curl -fs "http://localhost:$DASHBOARD_PORT/healthcheck" || dashboard_failed
+RESPONSE=$(curl -fs "http://localhost:$FAST_API_PORT/healthcheck")
+if [[ "$?" -ne 0 ]]; then
+	api_failed "$RESPONSE"
+fi
+
+RESPONSE=$(curl -fs "http://localhost:$DASHBOARD_PORT/healthcheck")
+if [[ "$?" -ne 0 ]]; then
+	dashboard_failed "$RESPONSE"
+fi
+
 exit 0
