- Converted the Dashboard components from JS to Python - Added dark mode to the dashboard - Switched to UUID v7 instead of v4 for improved search times - Added custom middleware to the API

diff --git a/docker-healthcheck b/docker-healthcheck
--- a/docker-healthcheck
+++ b/docker-healthcheck
@@ -1,5 +1,14 @@
 #!/bin/bash
 
-curl -fs "http://localhost:$FAST_API_PORT" || exit 1
-curl -fs "http://localhost:$DASHBOARD_PORT" || exit 1
+function api_failed() {
+	echo "API Healthcheck failed.";
+	exit 1
+}
+function dashboard_failed() {
+	echo "Dashboard Healthcheck failed.";
+	exit 1
+}
+
+curl -fs "http://localhost:$FAST_API_PORT/healthcheck" || api_failed
+curl -fs "http://localhost:$DASHBOARD_PORT/healthcheck" || dashboard_failed
 exit 0
